services:
  back-end:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
  front-end-dev:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
  vector-db-dev:
    volumes:
      - ./base/services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
